# name: GitHub Pages deploy

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# concurrency:
#   group: 'pages'
#   cancel-in-progress: false

# env:
#   app_output_dir: ./apps/doc/out

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup
#         uses: ./.github/workflows/setup

#       - name: Setup Pages
#         uses: actions/configure-pages@v4
#         with:
#           static_site_generator: next

#       - name: Build my App
#         run: pnpm run build --filter devlog && touch ${{ env.app_output_dir }}/.nojekyll

#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: ${{ env.app_output_dir }}

#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}

#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - name: Publish to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4
